---
title: "Project 2 README"
author: "other-carp"
date: "2022/5/10"
output: github_document
---

# Introduction

Russian-Ukraine crisis is a long lasting problem and it caused countless casualties nearly everyday. The earliest big confrontation can be dated back to 2014, when two cities from Ukraine (Donetsk and Luhansk) started revolution. From 2014 to 2022, there are several small military events and non-military but violent events happened at the boarder of Russia-Ukraine. In 2022, concerning the East expansion of NATO, Russia started a war against Ukraine and brings up the confrontation. Many people are killed and many cities are destroyed during the war. In this project, we want to build a shiny app to illustrate the military events happened during the recent 2022 Russia-Ukraine war and keep track of the territory boundary or military marching of soldiers from two sides.

We choose this topic because all of us are concerned about international confrontations. We hope that the world is peaceful and there is no war or violent event exist any more. Also, it would be interesting to take a look at the which place has the most attackers or military actions, and which side has the relative advantages as the battles continued. If we can plot every single events on a map, we will be able to discover some patterns such as which area or city has the most violent event happen and hopefully, we can prevent the same attacks from happening again. 

What we want to do is to use shiny app to live demonstrate the process of Russia-Ukraine war, including the territory movement, military and non-military events across different time frame. You can find more details on data frame below.


# Data




# Analysis/Graph Outline




## Graph 1



## Graph 2




## Discussion



