
## Packages
```{r packages}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sf)
library(units)
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 12))
```

## Load the data

```{r data}

mode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}



shp <- st_read("Data/shp_city/pp624tm0074.shp") %>%
  dplyr::select(name_1, name_2)


start <- "20220227"
end <- "20220501"

ctr_start <- paste0("ctr_", start_ctr)
ctr_end <- paste0("ctr_", end_ctr)

control <-  read_csv("Data/control_latest.csv") %>%
  dplyr::select(geonameid, longitude, latitude, 
         contains(ctr_start), contains(ctr_end)) %>%
  reshape2::melt(id.vars = c("longitude", "latitude", "geonameid"),
                 value.name = "control") %>%
  mutate(date = substr(variable, 5, 12),
         control = ifelse(control == "UA",1,
                          ifelse(control == "RU", 2, 3)))  %>%
  group_by(geonameid, longitude, latitude, date) %>%
  summarise(control = mode(control)) %>%
  st_as_sf(coords = c("longitude", "latitude"),
           crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") %>% 
  st_join(shp, left = FALSE) %>%
  st_drop_geometry() %>%
  group_by(name_1, name_2, date) %>%
  summarise(control = mode(control)) %>%
  mutate(control = ifelse(control == "1","UA",
                          ifelse(control == "2", "RU", "Contested"))) %>%
  spread(key = date, value = control) 

control$Country <- ifelse(get(start, control) == "UA" 
                                & get(end, control) == "RU", 
                                "UA2RU", "")
control$Country <- ifelse(get(start, control) == "RU" 
                                & get(end, control) == "UA", 
                                "RU2UA", control$Country)
control$Country <- ifelse(get(start, control) == get(end, control), 
                                get(start, control), control$Country)
control$Country <- ifelse(control$Country == "",
                                get(end, control), control$Country)
control$Country <- ifelse(is.na(control$Country), "UA", control$Country)

control <-  sp::merge(shp, control,
                      by = c("name_1", "name_2"), all=F)

ggplot(data = control) +
  geom_sf(aes(fill=Country)) +
  scale_fill_manual(values = c("RU" = "firebrick1",
                               "UA2RU" = "hotpink",
                               "UA" = "goldenrod1",
                               "RU2UA" = "yellow2",
                               "Contested"="blue"))


df_area <- control %>%
  mutate(area = st_area(.)) %>%
  st_drop_geometry() %>%
  dplyr::select(-Country) %>%
  reshape2::melt(id.vars = c("name_1", "name_2", "area"),
                 value.name = "control") %>%
  dplyr::rename(date = variable) %>%
  mutate(control = ifelse(is.na(control), "UA", control),
         area = drop_units(area)) %>%
  mutate(control = factor(control, levels= rev(c("UA", "RU", "Contested"))),
         date = factor(date)) %>%
  group_by(date, control) %>%
  dplyr::summarise(area = sum(area)) %>%
  group_by(date) %>%
  mutate(total_area = sum(area),
         prop = round(area/total_area,3)*100) %>%
  rename(Country = control)
    

ggplot(df_area,
       aes(y = prop, x = date)) +
  geom_flow(aes(alluvium = Country), alpha= .9, 
            lty = 2, fill = "white", color = "black",
            curve_type = "linear", 
            width = .5) +
  geom_col(aes(fill = Country), width = .5, color = "black") +
  scale_fill_manual(values = c("RU" = "firebrick1",
                               "UA" = "goldenrod1",
                               "Contested" = "blue")) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(title = "Percentage of area controled by each country",
       x = "Date",
       y = "Percentage")

```
